version: '3'
services:
  builder:
    image: emscripten/emsdk:4.0.5
    volumes:
      - ./docs:/app/docs
      - ./node:/app/node
      - ./src:/app/src
      - ./public:/app/public
      - ./wasi:/app/wasi
    working_dir: /app
